basePath: /v1
definitions:
  main.ShorternURLPayload:
    properties:
      long_url:
        type: string
    required:
    - long_url
    type: object
  store.URL:
    properties:
      created_at:
        type: string
      id:
        type: integer
      long_url:
        type: string
      short_url:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for URL Shorterner Service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: URL Shorterner API
paths:
  /urls/{shortURL}:
    get:
      consumes:
      - application/json
      description: Redirect to the original long URL based on the short url provided
        in the path
      parameters:
      - description: Short URL
        in: path
        name: shortURL
        required: true
        type: string
      produces:
      - application/json
      responses:
        "308":
          description: Permanent Redirect
          schema:
            type: string
        "404":
          description: URL not found
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      summary: Redirect to long URL
      tags:
      - urls
  /urls/shorten:
    post:
      consumes:
      - application/json
      description: Shortern an URL
      parameters:
      - description: URL payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.ShorternURLPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/store.URL'
        "400":
          description: Bad Request
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      security:
      - ApiKeyAuth: []
      summary: Shortern an URL
      tags:
      - urls
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
